---
# tasks file for graylog-sidecar

# Remove collector-sidecare
# yum remove collector-sidecar

- name: Stop collector-sidecar service
  service:
    name: collector-sidecar
    state: stopped
  ignore_errors: true

- name: Remove collector-sidecare
  yum: 
    name: collector-sidecar
    state: removed
  ignore_errors: true

# Clean collector-sidecar folders
# /etc/graylog/collector-sidecar
# /var/cache/graylog/collector-sidecar
# /var/log/graylog/collector-sidecar

- name: Clean-up old collector-sidecar files and folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/log/graylog/collector-sidecar
    - /var/cache/graylog/collector-sidecar
    - /etc/graylog/collector-sidecar

# Install graylog-sidecar 

- name: Download graylog-sidecar repository
  get_url:
    url: https://packages.graylog2.org/repo/packages/graylog-sidecar-repository-1-2.noarch.rpm
    dest: /tmp/graylog-sidecar-repository-1-2.noarch.rpm
    force: no

- name: Install graylog-sidecar repository
  yum:
    name: /tmp/graylog-sidecar-repository-1-2.noarch.rpm
    state: installed

- name: Install graylog-sidecar
  yum:
    name: graylog-sidecar
    state: installed
  register: graylog_sidecar_installed

- name: Install graylog-sidecard service
  shell: graylog-sidecar -service install
  when: graylog_sidecar_installed.changed

- name: Enable graylog-sidecar service
  service:
    name: graylog-sidecar
    enabled: yes

- name: Configure graylog-sidecar - server_url
  lineinfile:
    path: /etc/graylog/sidecar/sidecar.yml
    line: 'server_url: {{graylog_url}}'
  notify: restart graylog-sidecar

- name: Configure graylog-sidecar - server_api_token
  lineinfile:
    path: /etc/graylog/sidecar/sidecar.yml
    line: 'server_api_token: "{{graylog_api_token}}"'
  notify: restart graylog-sidecar

# Install Filebeat
# https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.8.1-x86_64.rpm

- name: Install filebeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.8.1-x86_64.rpm
    state: installed
  notify: restart graylog-sidecar

